name: Lint Workflow

on:
  push: 
    branches: ["main"]
  
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Build Application
        uses: ./.github/actions/build-application
      
      - name: Lint with flake8
        run: poetry run make check
